// Builds the single ES module a page loads: the custom element, its config
// reader, the orchestrator, the vendored marked, and both stylesheets, bundled
// into app/assets/javascripts/llm_meta_widget/llm-meta-widget.js.
//
// The artefact is COMMITTED and shipped in the gem, because a gem cannot run a
// build step on install. That means it can drift from its sources, so this
// script also runs as a check: `node script/build.mjs --check` rebuilds to a
// buffer and fails if the committed file differs. `npm test` runs that.
import { build } from "esbuild"
import { readFileSync } from "node:fs"
import { writeFileSync } from "node:fs"

const ENTRY = "app/assets/javascripts/llm_meta_widget/element.js"
const OUT = "app/assets/javascripts/llm_meta_widget/llm-meta-widget.js"
const BANNER =
  "// GENERATED by `npm run build` from element.js + config.js + auth.js + orchestrator.js" +
  " + marked.esm.js + conversation.css + panel.css.\n" +
  "// Do not edit this file; edit the sources and rebuild. `npm test` fails if it drifts.\n"

const check = process.argv.includes("--check")

const result = await build({
  entryPoints: [ ENTRY ],
  bundle: true,
  format: "esm",
  loader: { ".css": "text" },
  banner: { js: BANNER },
  write: false,
  logLevel: "warning",
})

const fresh = result.outputFiles[0].text
// Byte length, not the string's .length: `fresh` is a string, so .length counts
// UTF-16 code units and under-reports every non-ASCII character in the bundle (the
// em dashes in the UI strings alone cost 18). writeFileSync encodes it as UTF-8, so
// this is the size the file actually has on disk.
const bytes = Buffer.byteLength(fresh)

if (!check) {
  writeFileSync(OUT, fresh)
  console.log(`built ${OUT} — ${bytes} bytes`)
  process.exit(0)
}

let committed
try {
  committed = readFileSync(OUT, "utf8")
} catch {
  console.error(`${OUT} is missing. Run \`npm run build\`.`)
  process.exit(1)
}

if (committed !== fresh) {
  console.error(
    `${OUT} is stale: it does not match a fresh build of its sources.\n` +
    `Run \`npm run build\` and commit the result.`,
  )
  process.exit(1)
}
console.log(`${OUT} is up to date (${bytes} bytes)`)
